%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/kilted/.*$
%global __requires_exclude_from ^/opt/ros/kilted/.*$

Name:           ros-kilted-zenoh-security-tools
Version:        0.6.3
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS zenoh_security_tools package

License:        Apache License 2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kilted-rcpputils
Requires:       ros-kilted-rcutils
Requires:       ros-kilted-rmw
Requires:       ros-kilted-rmw-security-common
Requires:       ros-kilted-tinyxml2-vendor
Requires:       ros-kilted-zenoh-cpp-vendor
Requires:       ros-kilted-ros-workspace
BuildRequires:  json-devel
BuildRequires:  ros-kilted-rcpputils
BuildRequires:  ros-kilted-rcutils
BuildRequires:  ros-kilted-rmw
BuildRequires:  ros-kilted-rmw-security-common
BuildRequires:  ros-kilted-tinyxml2-vendor
BuildRequires:  ros-kilted-zenoh-cpp-vendor
BuildRequires:  ros-kilted-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  ros-kilted-ament-lint-auto
BuildRequires:  ros-kilted-ament-lint-common
%endif

%description
This package generates config files to enforce security with Zenoh

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/kilted" \
    -DAMENT_PREFIX_PATH="/opt/ros/kilted" \
    -DCMAKE_PREFIX_PATH="/opt/ros/kilted" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/kilted

%changelog
* Thu Aug 21 2025 Alejandro Hernanadez <alejandro@openrobotics.org> - 0.6.3-1
- Autogenerated by Bloom

* Wed Jun 18 2025 Alejandro Hernanadez <alejandro@openrobotics.org> - 0.6.2-1
- Autogenerated by Bloom

* Tue May 20 2025 Alejandro Hernanadez <alejandro@openrobotics.org> - 0.6.1-1
- Autogenerated by Bloom

* Tue Apr 22 2025 Alejandro Hernanadez <alejandro@openrobotics.org> - 0.6.0-2
- Autogenerated by Bloom

* Fri Apr 18 2025 Alejandro Hernanadez <alejandro@openrobotics.org> - 0.6.0-1
- Autogenerated by Bloom

