%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/jazzy/.*$
%global __requires_exclude_from ^/opt/ros/jazzy/.*$

%global __cmake_in_source_build 1

Name:           ros-jazzy-rmw-zenoh-cpp
Version:        0.2.8
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS rmw_zenoh_cpp package

License:        Apache License 2.0 and BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-jazzy-ament-index-cpp
Requires:       ros-jazzy-fastcdr
Requires:       ros-jazzy-rcpputils
Requires:       ros-jazzy-rcutils
Requires:       ros-jazzy-rmw
Requires:       ros-jazzy-rosidl-typesupport-fastrtps-c
Requires:       ros-jazzy-rosidl-typesupport-fastrtps-cpp
Requires:       ros-jazzy-tracetools
Requires:       ros-jazzy-zenoh-cpp-vendor
Requires:       ros-jazzy-ros-workspace
BuildRequires:  ros-jazzy-ament-cmake
BuildRequires:  ros-jazzy-ament-index-cpp
BuildRequires:  ros-jazzy-fastcdr
BuildRequires:  ros-jazzy-rcpputils
BuildRequires:  ros-jazzy-rcutils
BuildRequires:  ros-jazzy-rmw
BuildRequires:  ros-jazzy-rosidl-typesupport-fastrtps-c
BuildRequires:  ros-jazzy-rosidl-typesupport-fastrtps-cpp
BuildRequires:  ros-jazzy-tracetools
BuildRequires:  ros-jazzy-zenoh-cpp-vendor
BuildRequires:  ros-jazzy-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}
Provides:       ros-jazzy-rmw-implementation-packages(member)

%if 0%{?with_tests}
BuildRequires:  ros-jazzy-ament-lint-auto
BuildRequires:  ros-jazzy-ament-lint-common
%endif

%if 0%{?with_weak_deps}
Supplements:    ros-jazzy-rmw-implementation-packages(all)
%endif

%description
A ROS 2 middleware implementation using zenoh-cpp

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/jazzy" \
    -DAMENT_PREFIX_PATH="/opt/ros/jazzy" \
    -DCMAKE_PREFIX_PATH="/opt/ros/jazzy" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/jazzy

%changelog
* Sun Oct 05 2025 Yadunund <yadunund@openrobotics.org> - 0.2.8-1
- Autogenerated by Bloom

* Wed Sep 10 2025 Yadunund <yadunund@openrobotics.org> - 0.2.7-1
- Autogenerated by Bloom

* Thu Aug 21 2025 Yadunund <yadunund@openrobotics.org> - 0.2.6-1
- Autogenerated by Bloom

* Wed Jun 18 2025 Yadunund <yadunund@openrobotics.org> - 0.2.5-1
- Autogenerated by Bloom

* Sun Apr 20 2025 Yadunund <yadunund@openrobotics.org> - 0.2.4-1
- Autogenerated by Bloom

* Thu Mar 20 2025 Yadunund <yadunund@openrobotics.org> - 0.2.3-1
- Autogenerated by Bloom

* Wed Feb 19 2025 Yadunund <yadunund@openrobotics.org> - 0.2.2-1
- Autogenerated by Bloom

* Tue Feb 04 2025 Yadunund <yadunund@openrobotics.org> - 0.2.1-1
- Autogenerated by Bloom

* Thu Jan 02 2025 Yadunund <yadunund@openrobotics.org> - 0.2.0-1
- Autogenerated by Bloom

