%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/kilted/.*$
%global __requires_exclude_from ^/opt/ros/kilted/.*$

%global __cmake_in_source_build 1

Name:           ros-kilted-rmw-zenoh-cpp
Version:        0.6.0
Release:        2%{?dist}%{?release_suffix}
Summary:        ROS rmw_zenoh_cpp package

License:        Apache License 2.0 and BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kilted-ament-index-cpp
Requires:       ros-kilted-fastcdr
Requires:       ros-kilted-rcpputils
Requires:       ros-kilted-rcutils
Requires:       ros-kilted-rmw
Requires:       ros-kilted-rmw-test-fixture
Requires:       ros-kilted-rosidl-typesupport-fastrtps-c
Requires:       ros-kilted-rosidl-typesupport-fastrtps-cpp
Requires:       ros-kilted-tracetools
Requires:       ros-kilted-zenoh-cpp-vendor
Requires:       ros-kilted-ros-workspace
BuildRequires:  json-devel
BuildRequires:  ros-kilted-ament-cmake
BuildRequires:  ros-kilted-ament-index-cpp
BuildRequires:  ros-kilted-fastcdr
BuildRequires:  ros-kilted-rcpputils
BuildRequires:  ros-kilted-rcutils
BuildRequires:  ros-kilted-rmw
BuildRequires:  ros-kilted-rmw-test-fixture
BuildRequires:  ros-kilted-rosidl-typesupport-fastrtps-c
BuildRequires:  ros-kilted-rosidl-typesupport-fastrtps-cpp
BuildRequires:  ros-kilted-tracetools
BuildRequires:  ros-kilted-zenoh-cpp-vendor
BuildRequires:  ros-kilted-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}
Provides:       ros-kilted-rmw-implementation-packages(member)
Provides:       ros-kilted-rmw-test-fixture-implementation-packages(member)

%if 0%{?with_tests}
BuildRequires:  ros-kilted-ament-lint-auto
BuildRequires:  ros-kilted-ament-lint-common
%endif

%if 0%{?with_weak_deps}
Supplements:    ros-kilted-rmw-implementation-packages(all)
Supplements:    ros-kilted-rmw-test-fixture-implementation-packages(all)
%endif

%description
A ROS 2 middleware implementation using zenoh-cpp

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/kilted" \
    -DAMENT_PREFIX_PATH="/opt/ros/kilted" \
    -DCMAKE_PREFIX_PATH="/opt/ros/kilted" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/kilted

%changelog
* Tue Apr 22 2025 Yadunund <yadunund@openrobotics.org> - 0.6.0-2
- Autogenerated by Bloom

* Fri Apr 18 2025 Yadunund <yadunund@openrobotics.org> - 0.6.0-1
- Autogenerated by Bloom

* Thu Mar 20 2025 Yadunund <yadunund@openrobotics.org> - 0.5.0-1
- Autogenerated by Bloom

* Wed Feb 19 2025 Yadunund <yadunund@openrobotics.org> - 0.4.0-1
- Autogenerated by Bloom

* Tue Feb 04 2025 Yadunund <yadunund@openrobotics.org> - 0.3.1-1
- Autogenerated by Bloom

* Thu Jan 02 2025 Yadunund <yadunund@openrobotics.org> - 0.3.0-1
- Autogenerated by Bloom

